### ISSUE TITLE
App crashes in development on fresh install

### ISSUE THREAD

**Issue by gordonpn** [codebushi/gatsby-theme-docs#7]
I ran the exact three commands listed under [Getting Started](https://github.com/codebushi/gatsby-theme-document#getting-started) and got the following error:

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

```
  91 | const preferDefault = m => (m && m.default) || m
  92 | let Root = preferDefault(require(`./root`))
  93 | domReady(() => {
> 94 |   renderer(<Root />, rootElement, () => {
  95 |     apiRunner(`onInitialClientRender`)
  96 |   })
  97 | })
```

> The above error occurred in the <Context.Provider> component:
    in GlobalContextProvider (at gatsby-browser.js:5)
    in StaticQueryStore (at root.js:138)
    in _default (at app.js:94)

> Consider adding an error boundary to your tree to customize error handling behavior.

> Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

I have gatsby-cli@2.12.45 installed.

**Comment by rsexton404** [comment]
I had the same issue. A workaround is to clone this repo and use the files within `gatsby-theme-document/tree/master/gatsby-theme-document` as if it they were part of a Gatsby starter. Hope that helps! You'll have to run `npm install` before running `gatsby develop` for the first time.

**Comment by ChangoMan** [comment]
Thanks for reporting, @gordonpn @rsexton404  I just updated the packages in the main theme, can you try this again? I just tried and it seems to work okay for me.

*EDIT: Seems like it works for me because I'm using `Yarn`, and when I run `gatsby new` it's installing everything with `Yarn`. When I try using regular `npm install` it's not working for some reason. Might be a bug with Theme UI and the `gatsby-plugin-theme-ui` but I'm not quite sure.

**Comment by gordonpn** [comment]
Upgraded the dependencies and I'm getting this error now:

> Error: [useColorMode] requires the ColorModeProvider component

```
  86 | const { colorMode, setColorMode } = useThemeUI()
  87 | 
  88 | if (typeof setColorMode !== 'function') {
> 89 |   throw new Error(`[useColorMode] requires the ColorModeProvider component`)
  90 | }
  91 | 
  92 | return [colorMode, setColorMode]
```

In my case, I'm using npm and I've noticed this when I check the installed packages with `npm list --depth 0`

```
├── acorn@6.4.1
├── gatsby@2.23.3
├── gatsby-theme-document@1.0.10
├── react@16.13.1
├── react-dom@16.13.1
├── react-refresh@0.8.3
├── theme-ui@0.2.52
└── yup@0.27.0

npm ERR! peer dep missing: react@16.8.1, required by gatsby-interface@0.0.167
npm ERR! peer dep missing: react-dom@16.8.1, required by gatsby-interface@0.0.167
```

I'm not sure if it is at all related to be honest. If I install that exact version (16.8.1), then the other packages throw errors that I need a more recent react and react-dom.

**Comment by ChangoMan** [comment]
@gordonpn Can you try one more time, maybe start from scratch. I had to install theme-ui as a dependency to the example repo and now it's working for me.

**Comment by gordonpn** [comment]
I restarted from scratch and copied over the mdx files and everything. I can run `gatsby develop` and `gatsby build` without issues so far!

Thanks for your help, I'll close the issue now.
